name: Test and publish to PyPI

on:
  release:
    types:
      - created

jobs:
  test_and_publish:
    runs-on: ubuntu-latest
    steps:
    - name: Setup environment
      uses: actions/checkout@v3
    - run: pipx install poetry
    - run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - run: poetry install

    - name: Lint check
      run: make lint_ci
    - name: Run tests
      run: make test

    - name: Build package
      run: poetry build --format sdist

    - name: Publish to PyPI
      run: poetry publish
